# Installs the latest Python 3 version in Ubuntu using the deadsnakes ppa
- hosts: webservers
  become: true
  
  tasks:
# This task avoids downloading Python archive every time
  - name: Linux | Check if Python is present with the right version
    command: "}/etc/python3 --version"
    register: command_result
    ignore_errors: yes
    changed_when: false
    failed_when: false
 
     
  - name: Install prerequisites
    apt: name=python-software-properties state=present
    become: true

  - name: Add deadsnakes repo
    apt_repository: repo="ppa:deadsnakes/ppa"
    become: true

  - name: Install python
    apt: name="python3" state=present
    become: true

